player-messages:
    join: "&a+ &f%player%"
    leave: "&c- &8%player%"
    welcome: "&a+ &f%player% &bhas joined for the first time!"

command-messages:
    unknown: "&cUnknown command: &o/%command%"
    denied: "&cUnknown command: &o/%command%"
    usage: "&fUsage: %usage%"

command-sounds:
    unknown: BLOCK.NOTE_BLOCK.BASS
    denied: BLOCK.NOTE_BLOCK.BASS
    usage: BLOCK.NOTE_BLOCK.BASS

placeholders:
    replace-in-chat: true
    custom:
        secret: "&oEmpty Note..."

# ---------------------------------------------------------------------------------------------------
# ---------------------------------------- [[ Spawn Addon ]] ----------------------------------------
# ---------------------------------------------------------------------------------------------------
spawn:
    enabled: true
    cooldown: 5
    time: 3

    on-join: true
    on-death: true
    cancel-on-move: true

    tp-title: "&b&lSPAWN"
    tp-subtitle: "&3Teleporting in &f%time% &3seconds..."
    tp-sound: ENTITY.EXPERIENCE_ORB.PICKUP

    moved-message: "&cTeleportation cancelled due to movement!"
    cooldown-message: "&cYou need to wait %cooldown% more seconds!"
    deny-message: "&cYou can't teleport right now!"
    cancel-sound: BLOCK.NOTE_BLOCK.BASS

    locations:
        - { world: world, x: 124.5, y: 64, z: 10.5, yaw: 0, pitch: 0 }
        - { world: world, x: 124.5, y: 64, z: 10.5, yaw: 180, pitch: 0 }

# ---------------------------------------------------------------------------------------------------
# ---------------------------------------- [[ Drops Addon ]] ----------------------------------------
# ---------------------------------------------------------------------------------------------------
drops:
    display: "%value%%name%"
    display-format:
        value: "&7x&f%amount% "
        name: "%drop%"

    glow: true
    auto-pickup: false

    deny-message: "&cYou can't drop a %item%!"
    deny-sound: BLOCK.NOTE_BLOCK.BASS
    deny:
        - rare_sword
        - DIAMOND
    
    on-break:
        STONE:
            COBBLESTONE: 80
        GRAVEL:
            apple: 30
            rare_sword: 10
        COAL_ORE:
            rare_sword: 100

    break-restrictions-message: "&cYou need another tool to break a %block%!"
    break-restrictions-sound: BLOCK.NOTE_BLOCK.BASS
    break-restrictions:
        DIRT:
            - starter_pick
            - WOODEN_SHOVEL
            - STONE_SHOVEL
            - IRON_SHOVEL

# ---------------------------------------------------------------------------------------------------
# ---------------------------------------- [[ Items Addon ]] ----------------------------------------
# ---------------------------------------------------------------------------------------------------
items:
    types:
        - WEAPON,
        - ARMOR,
        - TOOL,
        - FOOD,
        - FUEL,
        - MISC,
        - ORE

    rarity:
        COMMON: "&7Common"
        UNCOMMON: "&aUncommon"
        RARE: "&bRare"
        EPIC: "&5Epic"
        LEGENDARY: "&eLegendary"

    format:
        name: "%name%"
        lore:
            - "%rarity% %luck%"
            - "%dupe%"
            - " "
            - "%attributes%"
            - " "
            - "%unbreakable%"
            - "%type%"

        unbreakable: "&3Unbreakable"
        type: "&8&o%value%"

        luck-default: "&câ­ &f%value%"
        luck:
            1: "&fâ­ &f%value%"
            30: "&aâ­â­ &f%value%"
            50: "&bâ­â­â­ &f%value%"
            100: "&dâ­â­â­â­ &f%value%"
            1000: "&eâ­â­â­â­â­ &f%value%"

        dupe:
            text: "%level% %chance%"

            chance-default: "&f%value%"
            chance:
                10: "&b%value%"

            level-default: "&cğŸŒŸ &f%value%"
            level:
                1: "&fğŸŒŸ &f%value%"
                2: "&ağŸŒŸğŸŒŸ &f%value%"
                3: "&bğŸŒŸğŸŒŸğŸŒŸ &f%value%"
                4: "&5ğŸŒŸğŸŒŸğŸŒŸğŸŒŸ &f%value%"
                5: "&eğŸŒŸğŸŒŸğŸŒŸğŸŒŸğŸŒŸ &f%value%"

        attributes-default: "&bğŸ’  &f%value%"
        attributes:
            MAX_HEALTH: "&câ¤ &f%value%"
            MOVEMENT_SPEED: "&bğŸ¿ &f%value%"
            SNEAKING_SPEED: "&bğŸ¿ &f%value%"

            ATTACK_DAMAGE: "&cğŸ—¡ &f%value%"
            ATTACK_SPEED: "&câŒ› &f%value%"
            ATTACK_KNOCKBACK: "&cğŸ—¡ &f%value%"
            KNOCKBACK_RESISTANCE: "&cğŸ›¡ï¸ &f%value%"

            ARMOR: "&bğŸ›¡ï¸ &f%value%"
            ARMOR_TOUGHNESS: "&bğŸ›¡ï¸ &f%value%"

            LUCK: "&ağŸ€ &f%value%"
            BLOCK_INTERACTION_RANGE: "&bğŸ›œ &f%value%"
            ENTITY_INTERACTION_RANGE: "&bğŸ›œ &f%value%"
            BLOCK_BREAK_SPEED: "&6â› &f%value%"
            MINING_EFFICIENCY: "&6â› &f%value%"
            SUBMERGED_MINING_SPEED: "&bğŸŒŠ &f%value%"

            SCALE: "&6ğŸ“ &f%value%"
            STEP_HEIGHT: "&6ğŸ“ &f%value%"
            GRAVITY: "&ağŸŒ &f%value%"
            JUMP_STRENGTH: "&ağŸŒ &f%value%"

            OXYGEN_BONUS: "&bğŸ«§ &f%value%"
            WATER_MOVEMENT_EFFICIENCY: "&bğŸŒŠ &f%value%"
            SPAWN_REINFORCEMENTS: "&2ğŸ• &f%value%"